package com.bidxi.gpsbrand.persistence;

import com.bidxi.gpsbrand.model.Title;

public interface TitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int insert(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int insertSelective(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    Title selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int updateByPrimaryKeySelective(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int updateByPrimaryKey(Title record);
}