package com.bidxi.gpsbrand.persistence;

import com.bidxi.gpsbrand.model.TitlePerson;
import org.apache.ibatis.annotations.Param;

public interface TitlePersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title_person
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int deleteByPrimaryKey(@Param("person_id") Long person_id, @Param("title_id") Long title_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title_person
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int insert(TitlePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title_person
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int insertSelective(TitlePerson record);
}