package com.bidxi.gpsbrand.persistence;

import com.bidxi.gpsbrand.model.TypePerson;

public interface TypePersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_person
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_person
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int insert(TypePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_person
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int insertSelective(TypePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_person
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    TypePerson selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_person
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int updateByPrimaryKeySelective(TypePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_person
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    int updateByPrimaryKey(TypePerson record);
}