package com.bidxi.gpsbrand.model;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.street
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.inside_number
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String insideNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.outside_number
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String outsideNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.colony
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String colony;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.zip_code
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.state_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer stateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.street
     *
     * @return the value of address.street
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.street
     *
     * @param street the value for address.street
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.inside_number
     *
     * @return the value of address.inside_number
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getInsideNumber() {
        return insideNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.inside_number
     *
     * @param insideNumber the value for address.inside_number
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setInsideNumber(String insideNumber) {
        this.insideNumber = insideNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.outside_number
     *
     * @return the value of address.outside_number
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getOutsideNumber() {
        return outsideNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.outside_number
     *
     * @param outsideNumber the value for address.outside_number
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setOutsideNumber(String outsideNumber) {
        this.outsideNumber = outsideNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.colony
     *
     * @return the value of address.colony
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getColony() {
        return colony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.colony
     *
     * @param colony the value for address.colony
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setColony(String colony) {
        this.colony = colony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.zip_code
     *
     * @return the value of address.zip_code
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.zip_code
     *
     * @param zipCode the value for address.zip_code
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.state_id
     *
     * @return the value of address.state_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Integer getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.state_id
     *
     * @param stateId the value for address.state_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }
}