package com.bidxi.gpsbrand.model;

public class Country {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.active
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer active;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.id
     *
     * @return the value of country.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.id
     *
     * @param id the value for country.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.name
     *
     * @return the value of country.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.name
     *
     * @param name the value for country.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.active
     *
     * @return the value of country.active
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.active
     *
     * @param active the value for country.active
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setActive(Integer active) {
        this.active = active;
    }
}