package com.bidxi.gpsbrand.model;

import java.util.Date;

public class Eventos {
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.id_evento
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer idEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.id_tipo_cultivo
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer idTipoCultivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.id_tipo_evento
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer idTipoEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.id_cultivo
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer idCultivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.lugar_evento
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String lugarEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.nombre_evento
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String nombreEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.fecha_evento
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Date fechaEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.enlace
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String enlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.nombre_imagen
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String nombreImagen;

    
    
    
    
    
    
    /**
     * @return the idEvento
     */
    public Integer getIdEvento() {
        return idEvento;
    }

    /**
     * @param idEvento the idEvento to set
     */
    public void setIdEvento(Integer idEvento) {
        this.idEvento = idEvento;
    }

    /**
     * @return the idTipoCultivo
     */
    public Integer getIdTipoCultivo() {
        return idTipoCultivo;
    }

    /**
     * @param idTipoCultivo the idTipoCultivo to set
     */
    public void setIdTipoCultivo(Integer idTipoCultivo) {
        this.idTipoCultivo = idTipoCultivo;
    }

    /**
     * @return the idTipoEvento
     */
    public Integer getIdTipoEvento() {
        return idTipoEvento;
    }

    /**
     * @param idTipoEvento the idTipoEvento to set
     */
    public void setIdTipoEvento(Integer idTipoEvento) {
        this.idTipoEvento = idTipoEvento;
    }

    /**
     * @return the idCultivo
     */
    public Integer getIdCultivo() {
        return idCultivo;
    }

    /**
     * @param idCultivo the idCultivo to set
     */
    public void setIdCultivo(Integer idCultivo) {
        this.idCultivo = idCultivo;
    }

    /**
     * @return the lugarEvento
     */
    public String getLugarEvento() {
        return lugarEvento;
    }

    /**
     * @param lugarEvento the lugarEvento to set
     */
    public void setLugarEvento(String lugarEvento) {
        this.lugarEvento = lugarEvento;
    }

    /**
     * @return the nombreEvento
     */
    public String getNombreEvento() {
        return nombreEvento;
    }

    /**
     * @param nombreEvento the nombreEvento to set
     */
    public void setNombreEvento(String nombreEvento) {
        this.nombreEvento = nombreEvento;
    }

    /**
     * @return the fechaEvento
     */
    public Date getFechaEvento() {
        return fechaEvento;
    }

    /**
     * @param fechaEvento the fechaEvento to set
     */
    public void setFechaEvento(Date fechaEvento) {
        this.fechaEvento = fechaEvento;
    }

    /**
     * @return the enlace
     */
    public String getEnlace() {
        return enlace;
    }

    /**
     * @param enlace the enlace to set
     */
    public void setEnlace(String enlace) {
        this.enlace = enlace;
    }

    /**
     * @return the nombreImagen
     */
    public String getNombreImagen() {
        return nombreImagen;
    }

    /**
     * @param nombreImagen the nombreImagen to set
     */
    public void setNombreImagen(String nombreImagen) {
        this.nombreImagen = nombreImagen;
    }
    
}