package com.bidxi.gpsbrand.model;

public class Genre {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column genre.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column genre.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column genre.id
     *
     * @return the value of genre.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column genre.id
     *
     * @param id the value for genre.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column genre.name
     *
     * @return the value of genre.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column genre.name
     *
     * @param name the value for genre.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}