package com.bidxi.gpsbrand.model;

import java.util.Date;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.email
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.last_name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.second_name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String secondName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.curp
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String curp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.rfc
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String rfc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.birthday
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.create_date
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.update_time
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.active
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.address_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Long addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.type_person_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Long typePersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.genre_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer genreId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.email
     *
     * @return the value of person.email
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.email
     *
     * @param email the value for person.email
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.last_name
     *
     * @return the value of person.last_name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.last_name
     *
     * @param lastName the value for person.last_name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.second_name
     *
     * @return the value of person.second_name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getSecondName() {
        return secondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.second_name
     *
     * @param secondName the value for person.second_name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setSecondName(String secondName) {
        this.secondName = secondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.curp
     *
     * @return the value of person.curp
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getCurp() {
        return curp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.curp
     *
     * @param curp the value for person.curp
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setCurp(String curp) {
        this.curp = curp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.rfc
     *
     * @return the value of person.rfc
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getRfc() {
        return rfc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.rfc
     *
     * @param rfc the value for person.rfc
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.birthday
     *
     * @return the value of person.birthday
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.birthday
     *
     * @param birthday the value for person.birthday
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.create_date
     *
     * @return the value of person.create_date
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.create_date
     *
     * @param createDate the value for person.create_date
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.update_time
     *
     * @return the value of person.update_time
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.update_time
     *
     * @param updateTime the value for person.update_time
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.active
     *
     * @return the value of person.active
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.active
     *
     * @param active the value for person.active
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.address_id
     *
     * @return the value of person.address_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.address_id
     *
     * @param addressId the value for person.address_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.type_person_id
     *
     * @return the value of person.type_person_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Long getTypePersonId() {
        return typePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.type_person_id
     *
     * @param typePersonId the value for person.type_person_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setTypePersonId(Long typePersonId) {
        this.typePersonId = typePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.genre_id
     *
     * @return the value of person.genre_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Integer getGenreId() {
        return genreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.genre_id
     *
     * @param genreId the value for person.genre_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setGenreId(Integer genreId) {
        this.genreId = genreId;
    }
}