package com.bidxi.gpsbrand.model;

public class Title {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.active
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer active;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.id
     *
     * @return the value of title.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.id
     *
     * @param id the value for title.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.name
     *
     * @return the value of title.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.name
     *
     * @param name the value for title.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.active
     *
     * @return the value of title.active
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.active
     *
     * @param active the value for title.active
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setActive(Integer active) {
        this.active = active;
    }
}