package com.bidxi.gpsbrand.model;

public class TitlePerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_person.person_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_person.title_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Long titleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_person.person_id
     *
     * @return the value of title_person.person_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_person.person_id
     *
     * @param personId the value for title_person.person_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_person.title_id
     *
     * @return the value of title_person.title_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Long getTitleId() {
        return titleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_person.title_id
     *
     * @param titleId the value for title_person.title_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setTitleId(Long titleId) {
        this.titleId = titleId;
    }
}