package com.bidxi.gpsbrand.model;

public class TypePerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_person.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_person.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_person.id
     *
     * @return the value of type_person.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_person.id
     *
     * @param id the value for type_person.id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_person.name
     *
     * @return the value of type_person.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_person.name
     *
     * @param name the value for type_person.name
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}