package com.bidxi.gpsbrand.model;

public class UserProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.profile_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Integer profileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.user_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.profile_id
     *
     * @return the value of user_profile.profile_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Integer getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.profile_id
     *
     * @param profileId the value for user_profile.profile_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.user_id
     *
     * @return the value of user_profile.user_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.user_id
     *
     * @param userId the value for user_profile.user_id
     *
     * @mbggenerated Wed Mar 02 18:27:17 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}